### PR TITLE
py3 support

### PR DESCRIPTION
**Pull request by asenchenko**
Adds  python3 support.

### CODE REVIEW

**Comment by cpascual** [comment]
Nice!  thanks for the PR

I'll test it ASAP (after the debian release of taurus & sardana)

**Comment by mrosanes** [comment]
Hi @asenchenko, thanks for the PR

I began testing it in a conda environment with python3.
- I could install it correctly using pip (pip install .) and make the import correctly:  from taurus.qt.qtgui import tpg

- Removing "from past.utils import old_div" I think is great.

- One difference that I see regarding master branch tested on python2; is that in python2 and master branch I can call 'python plot.py' and 'python trend.py'. In the PR I get an import problem: 

<pre>
from .curvespropertiestool import CurvesPropertiesTool
SystemError: Parent module '' not loaded, cannot perform relative import
</pre>

**Comment by asenchenko** [comment]
In python 2, `from __future__ import absolute_import` disables implicit relative imports. All modules with `__name__=='__main__'` is considered as top-level. 

We have two option:
1) To replace relative import with absolute.
2) To move all code in `if __name__ == '__main__': ` section to different place.

**Comment by mrosanes** [comment]
Following with the review of python3 branch, also detected issue when adding curve to plot:
https://github.com/taurus-org/taurus_pyqtgraph/issues/6

**Comment by mrosanes** [comment]
(tested with pyqt4):
- taurus_pyqtgraph/taurus_pyqtgraph/examples works correctly
- taurusimageitem works correctly

**Comment by cpascual** [comment]
I've checked with:

```console
python -m taurus.qt.qtgui.graphic.jdraw.jdraw_view ~/src/taurus/lib/taurus/qt/qtgui/graphic/jdraw/test/res/SimpleScalarViewer.jdw
```

In the develop version, this works only for python2 and PyQt4 and it fails for py3+qt4, py3+qt5, py2+qt5
... whicle with this PR, it works for all combinations, so I am merging.

Thanks!

**Comment by cpascual** [comment]
Hi @asenchenko , sorry: I merged this PR by mistake. I already reverted the merge. 
Could you check if you can reopen the merge request?
If not, we can create a new PR from the same branch. Sorry for the iconveniences

**Comment by asenchenko** [comment]
> Hi @asenchenko , sorry: I merged this PR by mistake. I already reverted the merge.
> Could you check if you can reopen the merge request?
> If not, we can create a new PR from the same branch. Sorry for the iconveniences

I can't reopen PR. If i'm trying to create new PR, github says: **"There isn’t anything to compare. taurus-org:master is up to date with all commits from asenchenko:dev_python3_master. Try switching the base for your comparison."**

**Comment by cpascual** [comment]
Ok, don't worry. I'll try to fix the mess that I caused and let you know

sorry again...

**Comment by cpascual** [comment]
Well... I found no better solution than to force-push the master branch to the point previous to my mess-up and create a new PR (#11) from the same branch as this one (so let's continue the work in #11).

The only thing to keep in mind is that:

 **if you have updated your local master branch from the one in https://github.com/taurus-org/taurus_pyqtgraph/ today (2019-03-20) between 15:30 and 18:55 (GMT+1), you should better remove your local branch and check it out fresh now.**

Once again, sorry for all these inconveniences.

PS: It should not be necessary to ever use it, but just in case: before force-pushing, I pushed the messed-up master branch to https://github.com/cpascual/taurus_pyqtgraph/tree/oldmaster

**Pull request merged**
